n = int(input("Enter a number: "))
p = n
print("Largest: " + str(p))
n = int(input("Enter a number: "))
p = max(p,n)
print("Largest: " + str(p))
n = int(input("Enter a number: "))
p = max(p,n)
print("Largest: " + str(p))
n = int(input("Enter a number: "))
p = max(p,n)
print("Largest: " + str(p))
n = int(input("Enter a number: "))
p = max(p,n)
print("Largest: " + str(p))
n = int(input("Enter a number: "))
p = max(p,n)
print("Largest: " + str(p))
